#!/usr/bin/env php
<?php
define('ROOT', __DIR__ . '/..');
require ROOT . '/vendor/autoload.php';

use Wumpa\Component\Console\Console;

$application = new Console('Wumpa console', '0.1');
$application->run();
